name: History Hub
on:
  # web hook event that is corresponding to actions in every spoke repo
  repository_dispatch:
    types: [readme_updated]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      INFRA_TITLE: "## Infra implementation history"
      INFRA_MARKER: "![Infra badge](https://img.shields.io/badge/infra-7B42BC)"
    steps:

    # Fetch README.md from infra-repo
    - name: Checkout infra-repo
      uses: actions/checkout@v3
      with:
        repository: Smile2Buy/s2b-infra
        sparse-checkout: |
          README.md
        sparse-checkout-cone-mode: false
        path: infra
        token: ${{ secrets.PAT }}

    # Fetch origin; Smile2Buy/.github
    - name: Checkout
      uses: actions/checkout@v3

    # Copy skeleton as base
    - name: Copy skeleton
      run: |
        cp -f skeleton/README.md profile/README.md

    # Append done items from infra-repo
    - name: Append history of infra
      run: |
        echo "$INFRA_TITLE" > profile/README.md
        cat infra/README.md \
          | perl -lne 'print if /^(\s*- \[[x]\]|#{3,})/' \
          | sed "s#- \[x\]#- $INFRA_MARKER#" >> profile/README.md
        rm -rf infra

    # Create PR
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        commit-message: "docs: history-hub updated"
        title: "docs: History-hub updated ${GITHUB_RUN_NUMBER}th"
