name: History Hub
on:
  # web hook event that is corresponding to actions in every spoke repo
  repository_dispatch:
    types: [readme_updated]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      INFRA_TITLE: "## Infra implementation history"
      INFRA_MARKER: "![Infra badge](https://img.shields.io/badge/infra-7B42BC)"
    steps:
    - name: Checkout README.md of infra-spoke-repo under /infra path
      uses: actions/checkout@v3
      with:
        repository: Smile2Buy/s2b-infra
        sparse-checkout: |
          README.md
        sparse-checkout-cone-mode: false
        path: infra
        token: ${{ secrets.PAT }}

    - name: Check if README.md of infra-spoke-repo checkouted well
      run: |
        cat infra/README.md

    - name: Checkout whole contents of hub-repo under /hub path
      uses: actions/checkout@v3
      with:
        path: hub

    - name: Check if to-be-updated README.md of hub-repo checkouted well
      run: |
        cat hub/profile/README.md

    - name: Check if README.md of infra-spoke-repo is still accessible
      run: |
        cat infra/README.md

    - name: Overwrite content of to-be-updated README.md to skeleton-base
      run: |
        cp -f hub/skeleton/README.md hub/profile/README.md

    - name: Check if previous readme replaced by skeleton well
      run: |
        cat hub/profile/README.md

    - name: Test1; if shell script works well
      run: |
        cat infra/README.md

    - name: Test2; if shell script works well
      run: |
        cat infra/README.md \
          | perl -lne 'print if /^(\s*- \[[x]\]|#{3,})/'

    - name: Test3; if shell script works well
      run: |
        cat infra/README.md \
          | perl -lne 'print if /^(\s*- \[[x]\]|#{3,})/' \
          | sed "s#- \[x\]#- $INFRA_MARKER#"

    - name: Append title of infra-spoke history
      run: |
        echo "$INFRA_TITLE" >> hub/profile/README.md

    - name: Cherry-pick done items from infra-repo and plant to updating REAME.md
      run: |
        cat infra/README.md \
          | perl -lne 'print if /^(\s*- \[[x]\]|#{3,})/' \
          | sed "s#- \[x\]#- $INFRA_MARKER#" >> hub/profile/README.md

    - name: Check if infra-spoke history appended well
      run: |
        cat hub/profile/README.md

    # Create PR
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        commit-message: "docs: history-hub updated"
        title: "docs: History-hub updated ${GITHUB_RUN_NUMBER}th"
        path: hub
