name: History Hub
on:
  # web hook event that is corresponding to actions in every spoke repo
  repository_dispatch:
    types: [readme_updated]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      INFRA_TITLE: "## Infra implementation history"
      INFRA_MARKER: "![Infra badge](https://img.shields.io/badge/infra-7B42BC)"
    steps:
    - name: Check out
      uses: actions/checkout@v3

    # Occupied, should create whenever added new spoke
    - name: Check out infra-repo
      uses: actions/checkout@v3
      with:
        repository: Smile2Buy/s2b-infra
        path: infra
        token: ${{ secrets.PAT }}

    - name: Generate merged README.md
      run: |
        cp -f skeleton/README.md profile/README.md
        echo "$INFRA_TITLE" > profile/README.md
        cat infra/README.md \
          | perl -lne 'print if /^(\s*- \[[x]\]|#{3,})/' \
          | sed "s#- \[x\]#- $INFRA_MARKER#" >> profile/README.md

    - name: Create Pull Request
      run: |
        git config --local user.emal "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b changes-branch
        git add .
        git commit -m "docs: history across org has been merged"
        gh pr create \
          --title "docs: History-hub updated by ${GITHUB_RUN_NUMBER}" \
          --body "" \
          --base main \
          --head changes-branch \
          --repo ${{ github.repository }}
      env:
        GH_TOKEN: ${{ secrets.PAT }}


